var streamteams=
{"QLD":"Queensland",
"NSW":"New South Wales",
"VIC":"Victoria",
"TAS":"Tasmania",
"ACT":"Australian Capital Territory",
"WA":"Western Australia",
"NT":"Northern Territory",
"SA":"South Australian",
"XGYM":"X Gym",
"CS":"City Strength",
"WD":"Wellness Department",
"OMNI":"Omni Fitness",
"AA":"Adonis Athletics",
"ALP":"Alpha Athletes",
"WC":"Wellness Central",
"OF":"Omega Fitness",
"NB":"Newcastle Barbell",
"CB":"Cornell Barbell"}
